#!/bin/bash
# Miroimage Server script

CUDA_VISIBLE_DEVICES=0 \
MIROIMAGE_HOST=0.0.0.0 \
MIROIMAGE_PORT=8081 \
MIROIMAGE_MODEL_PATH=Qwen/Qwen-Image-Edit-2511 \
MIROIMAGE_MODEL_NAME=Qwen-Image-Edit-2511 \
MIROIMAGE_NUM_INFERENCE_STEPS=50 \
MIROIMAGE_CFG_SCALE=4.0 \
MIROIMAGE_GUIDANCE_SCALE=1.0 \
MIROIMAGE_LAYERS=4 \
MIROIMAGE_RESOLUTION=640 \
python3 servers/miroimage_server.py
